# Generated by Django 5.2.3 on 2025-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_agent", "0003_remove_batch_discarded_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="cost",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
