# Generated by Django 5.2.3 on 2025-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_agent", "0004_problem_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="total_cost",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
