# Generated by Django 5.2.3 on 2025-06-19 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("math_agent", "0005_batch_total_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="total_cost",
        ),
    ]
