# Generated by Django 5.2.3 on 2025-06-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_agent", "0006_remove_batch_total_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Batches"},
        ),
        migrations.AddField(
            model_name="batch",
            name="batch_cost",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="batch",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="batch",
            name="number_of_valid_needed",
            field=models.IntegerField(),
        ),
    ]
