# Generated by Django 5.2.3 on 2025-06-19 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_agent", "0007_alter_batch_options_batch_batch_cost_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name_plural": "Batches"},
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_cost",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="batch",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="batch",
            name="number_of_valid_needed",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
